# Solution: Pandas - Manipuler et analyser vos données

Cet exercice utilisera le dataset `mtcars` qui comprend 32 observations sur 11 variables : 

0. **mpg** Miles/(US) gallon
0. **cyl** Number of cylinders
0. **disp** Displacement (cu.in.)
0. **hp** Gross horsepower
0. **drat** Rear axle ratio
0. **wt** Weight (1000 lbs)
0. **qsec** 1/4 mile time
0. **vs** Engine (0 = V-shaped, 1 = straight)
0. **am** Transmission (0 = automatic, 1 = manual)
0. **gear** Number of forward gears
0. **carb** Number of carburators

## Importer les librairies

In [1]:
import numpy as np
import scipy
import pandas as pd
from pandas import Series, DataFrame
import seaborn as sb
from scipy import stats

## Manipuler un dataframe

Il est important de savoir manipuler un dataframe afin de pouvoir l'analyser et éventuellement en adapter la structure aux besoin à venir.

### Initialisation à partir d'un fichier

Utilisez la fonction [pandas.read_csv](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) afin d'initialiser un dataframe à patir des données lues dans le fichier `data/mtcars.csv`

Vous afficherez les 10 premières lignes de ce dataframe en utilisant [pandas.DataFrame.head](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.head.html)

In [2]:
# TODO
# Initialisez un dataframe à partir du fichier 'mtcars.csv'
# Affichez les dix premières lignes de ce dataframe

cars = pd.read_csv("../../data/mtcars.csv")

cars.head(10)

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4

### Initialisation statique

Il arrivera régulièrement que vous ayez besoin de créer des dataframes à partir de données en dur dans votre code. Le format JSON est utilisé à ces fins :

```python
{
    'id': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    'client': ['client1','client2','client3','client4','client5','client6','client7','client8','client9','client10'],
    'montant': [50,45,98,125,456,41,25,4,89,42]
}
```

décrit un dataframe ayant 3 colonnes `id`, `client` et `montant`. Le dataframe contient 10 lignes
> Les valeurs sont fournies colonne par colonne !

A partir de la documentation de [DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html), initialisez un dataframe ayant trois colonnes : `facture_id`, `client_id` et `montant`. Ce dataframe contiendra les données du document json ci-dessus.

In [3]:
# TODO initialisation d'un dataframe :
factures = pd.DataFrame({
    'facture_id': [100, 200, 300, 400, 500, 600, 700, 800, 900,1000],
    'client_id': ['client1','client2','client3','client4','client5','client6','client7','client8','client9','client10'],
    'montant': [50,45,98,125,456,41,25,4,89,42]
})[['facture_id','client_id',"montant"]]

# TODO : Affichez les données du dataframe
factures

   facture_id client_id  montant
0         100   client1       50
1         200   client2       45
2         300   client3       98
3         400   client4      125
4         500   client5      456
5         600   client6       41
6         700   client7       25
7         800   client8        4
8         900   client9       89
9        1000  client10       42

### Dataframes et Indexes

Les lignes d'un dataframe sont toujours indexées afin de permettre de les référencer.
Par défaut, l'index d'un dataframe est une suite consécutive d'entier : 0, 1, 2, ...

Le type et la valeur d'un index peuvent être modifiés : `df.set_index(colname)`

* Affichez la ligne associée à l'index 5 dans le dataframe `cars`

In [4]:
cars.loc[5]

model    Valiant
mpg         18.1
cyl            6
disp       225.0
hp           105
drat        2.76
wt          3.46
qsec       20.22
vs             1
am             0
gear           3
carb           1
Name: 5, dtype: object

* Affichez la valeur de la colonne `gear` de la ligne associée à l'index 5 dans le dataframe `cars`

In [5]:
cars.loc[5]['gear']

3

* Proposez une colonne du dataframe `factures` pour servir d'index. Modifiez le dataframe en conséquence

In [6]:
factures = factures.set_index('facture_id')
factures

           client_id  montant
facture_id
100          client1       50
200          client2       45
300          client3       98
400          client4      125
500          client5      456
600          client6       41
700          client7       25
800          client8        4
900          client9       89
1000        client10       42

### Slicing


Exemples :

```python
df.iloc[1:3,:]  # Retourne un dataframe référencant les ligne 1 à 2 et toutes les colonnes 
df.iloc[-1,:]   # Retourne un dataframe contenant la dernière ligne du dataframe (par index)
df.loc[3:7,['col1','col5']] # Retourne un dataframe référencant les ligne 3 à 7 et les colonnes 'col1' et 'col5' (par nom de colonne)
df.loc[3:7,'col1':'col5'] # Retourne un dataframe référencant les ligne 3 à 7 et les colonnes 'col1' à 'col5' (par nom de colonne)
```

In [7]:
# TODO
# Faîtes afficher la valeurs des cellules des lignes de 2 à 5 pour les colonnes 1 à 2 du dataframe `cars`
cars.iloc[2:6,1:3]

    mpg  cyl
2  22.8    4
3  21.4    6
4  18.7    8
5  18.1    6

In [8]:
# TODO
# Faites afficher la valeurs des cellules des colonnes allant de 'cyl' à 'drat'
# pour les lignes 1 à 3 du dataframe `cars`
cars.loc[1:3,'cyl':'drat']

   cyl   disp   hp  drat
1    6  160.0  110  3.90
2    4  108.0   93  3.85
3    6  258.0  110  3.08

In [9]:
# TODO
# Faîtes afficher toutes les colonnes de l'avant dernière ligne du dataframe `cars`
cars.iloc[-2,:]

model    Maserati Bora
mpg               15.0
cyl                  8
disp             301.0
hp                 335
drat              3.54
wt                3.57
qsec              14.6
vs                   0
am                   1
gear                 5
carb                 8
Name: 30, dtype: object

### Sélectionner des lignes & colonnes : Boolean indexing

Il s'agit d'une méthode de filtrage des données de votre dataset. Le filtre utilisé est multi-colonne. La syntaxe est la suivante :

```python
df.loc [ ( df['col_to_test'] == val)  , [ col1_to_return , col2_to_return , ... ] ]
```

In [10]:
# TODO
# Initialisez un nouveau dataframe qui référencera les colonnes `models`
# et `am` du dataframe `cars` respectant les critères suivants :
#    am == 0
#    gear == 3
cars2 = cars.loc[(cars['am']==0) & (cars['gear']==3), ['model','am']]

# TODO : affichez le dataframe créé
cars2

                  model  am
3        Hornet 4 Drive   0
4     Hornet Sportabout   0
5               Valiant   0
6            Duster 360   0
11           Merc 450SE   0
12           Merc 450SL   0
13          Merc 450SLC   0
14   Cadillac Fleetwood   0
15  Lincoln Continental   0
16    Chrysler Imperial   0
20        Toyota Corona   0
21     Dodge Challenger   0
22          AMC Javelin   0
23           Camaro Z28   0
24     Pontiac Firebird   0

In [11]:
# A quoi sert la ligne de code suivante ?
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   model   32 non-null     object
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64
 9   am      32 non-null     int64
 10  gear    32 non-null     int64
 11  carb    32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

## Synthétiser vos données avec Pandas

### Somme des colonnes

In [12]:
# TODO
# Procédez à la somme des données de chacune des colonnes du dataframe `factures`
# Quels sens donnez vous au résultat ?
factures.sum()

client_id    client1client2client3client4client5client6clie...
montant                                                    975
dtype: object

In [13]:
factures

           client_id  montant
facture_id
100          client1       50
200          client2       45
300          client3       98
400          client4      125
500          client5      456
600          client6       41
700          client7       25
800          client8        4
900          client9       89
1000        client10       42

In [14]:
# TODO
# Procédez à la somme de l'ensemble des données de chacune des lignes du dataframe `factures`
# Quels sens donnez vous au résultat ?
factures.sum(axis=1, numeric_only=True)

facture_id
100      50
200      45
300      98
400     125
500     456
600      41
700      25
800       4
900      89
1000     42
dtype: int64

In [15]:
# TODO
# Procédez au calcul de la valeur médiane de chacune des colonnes du dataframe `cars`
cars.median(numeric_only=True)

mpg      19.200
cyl       6.000
disp    196.300
hp      123.000
drat      3.695
wt        3.325
qsec     17.710
vs        0.000
am        0.000
gear      4.000
carb      2.000
dtype: float64

In [16]:
# TODO
# Procédez à la valeur moyenne de l'ensemble des données des colonnes du dataframe `cars`
# Quels sens donnez vous au résultat ?
cars.mean(numeric_only=True)

mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64

In [17]:
# TODO
# Déterminez la valeur maximale de chacune des colonnes du dataframe `cars`
# Quels sens donnez vous au résultat ?
cars.max(numeric_only=True)

mpg      33.900
cyl       8.000
disp    472.000
hp      335.000
drat      4.930
wt        5.424
qsec     22.900
vs        1.000
am        1.000
gear      5.000
carb      8.000
dtype: float64

## Synthétiser vos données catégorielles avec Pandas

In [18]:
# TODO
# Faites en sorte que la colonne 'model' du dataframe 'cars' soit utilisée comme index
cars.index = cars.model

[Documentation](https://pandas.pydata.org/pandas-docs/version/0.21/generated/pandas.Series.value_counts.html)

In [19]:
cars

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
model,,,,,,,,,,,,
Mazda RX4,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Valiant,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Duster 360,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Merc 240D,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Merc 230,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 280,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Merc 280C,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Merc 450SE,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SLC,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Cadillac Fleetwood,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Lincoln Continental,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Chrysler Imperial,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Fiat 128,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Honda Civic,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Toyota Corolla,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Toyota Corona,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Dodge Challenger,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
AMC Javelin,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Camaro Z28,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Pontiac Firebird,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Fiat X1-9,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Porsche 914-2,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Lotus Europa,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Ford Pantera L,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Ferrari Dino,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Maserati Bora,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Volvo 142E,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [20]:
# TODO
# Combien de voitures ont le même nombre de carburateur ('carb')
carb = cars.carb
carb.value_counts()

carb
4    10
2    10
1     7
3     3
6     1
8     1
Name: count, dtype: int64

In [21]:
# Afin de simplifier l'explication sur la méthode groupby, nous isolons un sous ensemble du dataframe initial
cars_cat = cars[['cyl','vs','am','gear','carb']]
cars_cat.head()


# Avec l'aide de votre formateur, analysez le résultat du code suivant
gears_group = cars_cat.groupby('gear')
gears_group.describe()

       cyl                                                 vs            ...  \
     count      mean       std  min  25%  50%  75%  max count      mean  ...
gear                                                                     ...
3     15.0  7.466667  1.187234  4.0  8.0  8.0  8.0  8.0  15.0  0.200000  ...
4     12.0  4.666667  0.984732  4.0  4.0  4.0  6.0  6.0  12.0  0.833333  ...
5      5.0  6.000000  2.000000  4.0  4.0  6.0  8.0  8.0   5.0  0.200000  ...

       am       carb
      75%  max count      mean       std  min  25%  50%  75%  max
gear
3     0.0  0.0  15.0  2.666667  1.175139  1.0  2.0  3.0  4.0  4.0
4     1.0  1.0  12.0  2.333333  1.302678  1.0  1.0  2.0  4.0  4.0
5     1.0  1.0   5.0  4.400000  2.607681  2.0  2.0  4.0  6.0  8.0

[3 rows x 32 columns]

### Transformer une variable en une variable catégorielle

In [22]:
# TODO 
# Affichez le type de la colonne 'am'
cars.am.dtype

dtype('int64')

Dans un dataframe, un colonne est de type [Serie](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html). En parcourant la documentation, affichez les valeurs différentes ainsi que leur nombre de la colonne 'am'

In [23]:
# TODO
# Combien de valeurs différentes y-a t'il dans la colonne 'am' ?
cars.am.value_counts()

am
0    19
1    13
Name: count, dtype: int64

In [24]:
# TODO
# Rajoutez une colonne 'am_cat' qui sera de type category et qui sera valorisée à partir de la colonne 'am'
cars['am_cat'] = pd.Series(cars.am, dtype="category")
#cars['am_cat'] = cars.am.astype('category')
cars['am_cat'].dtypes

CategoricalDtype(categories=[0, 1], ordered=False, categories_dtype=int64)

In [25]:

# On aurait pu simplement modifier le type de la colonne 'am', mais on préfère rajouter une colonne pour ne pas
# perdre l'originale
cars['am'] = cars.am.astype('category')

### Croiser les données catégorielle avec un crosstab
Interprétez le résultat du code suivant

In [26]:
pd.crosstab(cars['am'], cars['gear'])

gear   3  4  5
am
0     15  4  0
1      0  8  5

### Apply

La fonction [pandas.Series.apply](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.apply.html) est très souvent utilisée. Elle permet d'appliquer une fonction à l'ensemble des valeurs d'une colonne d'un dataframe (qui est de type `Serie`) : Cette fonction peut-être standard (i.e. fournie par Python), ou d'une fonction que vous aurez implémentée selon vos besoin.

* La fonction `apply` retourne une `Serie` (i.e. une colonne) qui est souvent affectée à une nouvelle colonne du dataframe d'origine.
* Elle prend une fonction `thefunc` en paramètre
* `thefunc` sera appelée autant de fois qu'il y a de lignes dans la `Serie`sur laquelle on l'applique
* le paramétre de `thefunc` correspond à la valeur de l'élément en cours de traitement dans la `Serie`en cours


**Exemple 1** :

```python
def nb_mots(s):
    return len(s.split(' '))

dataframe['nb_word'] = dataframe['sentence'].apply(nb_mots)
```

**Exemple 2** :

En déclarant une lambda expression (i.e. une fonction anonyme) : 

```python
dataframe['nb_word'] = dataframe['sentence'].apply(lambda s: len(s.split(' ')))

```

In [29]:
# TODO : Créez une colonne 'conso' (kilomètre / litre) dont la valeur sera calculée
# à partir de la colonne existante 'mpg'
# https://www.mpgtolitres.com/mpg-to-kml

def convert(x):
    result = x * 0.425143707
    return result 

cars['conso'] = cars['mpg'].apply(lambda s: s * 0.42)
cars.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,am_cat,conso
model,,,,,,,,,,,,,,
Mazda RX4,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,1,8.820
Mazda RX4 Wag,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,1,8.820
Datsun 710,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,1,9.576
Hornet 4 Drive,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,0,8.988
Hornet Sportabout,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,0,7.854

In [30]:
pd.crosstab(cars['am'], cars['gear'])

gear   3  4  5
am
0     15  4  0
1      0  8  5

In [ ]:
# TODO : Créez une colonne 'conso' (kilomètre / litre) dont la valeur sera calculée à partir de la colonne existante 'mpg'
# https://www.mpgtolitres.com/mpg-to-kml
def convert(x):
    result = x *0.425143707
    return result 

cars['conso'] = cars['mpg'].apply(lambda s: convert(s))

In [ ]:
cars.head()